# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.0-beta.1
group=tnpl.fractureddimensions
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Fractured Dimensions
mod_author=tnpl
mod_id=fractured_dimensions
license=MIT
credits=
description=The description of your mod. \nAccepts multilines.
minecraft_version_range=[26.1.2, 26.2)
neo_form_version=26.1.2-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.148.2+26.1.2
fabric_loader_version=0.19.2

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.48-beta
neoforge_loader_version_range=[4,)

# Dependencies
reg_version=26.1-0.1.0
jei_version=29.5.0.28
jade_version_fabric=26.1.0+fabric
jade_version_neoforge=26.1.1+neoforge

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
